export enum AppEventType {
  ENTER_PAGE = "ENTER_PAGE",
  USER_PENSION_SUBMITTED = "USER_PENSION_SUBMITTED",
  USER_FORM_CREATED = "USER_FORM_CREATED",
  USER_FORM_UPDATED = "USER_FORM_UPDATED",
  USER_SUMMARY_GENERATED = "USER_SUMMARY_GENERATED",
}
